spring: 
  profiles: 
  active: 
  - dev
---
spring: 
  profiles: dev  #开发环境
  application: 
    name: cloudparent-config-dev

---
spring: 
  profiles: test  #测试环境
  application: 
    name: cloudparent-config-test

#必须utf-8格式保存，否则出错