spring: 
  profiles: 
    active: 
    - dev

---

server:
  port: 7001
spring: 
  profiles: dev
    application: 
      name: cloudparent-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #不在注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，维护服务示例不去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://eureka7001.com:7001/eureka/

---

server:
  port: 7011
spring: 
  profiles: test
    application: 
      name: cloudparent-config-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #不在注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，维护服务示例不去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7011/eureka/